update Russian translation
MiyooCFW/gmenu2x pull request #53
Opened 2023-12-23 22:27 UTC by MayanKoyote

Making changes related to commit 33d9fdd.
Spelling error correction.

2023-12-24 13:54 UTC, Apaczer requested changes

2023-12-24 13:54 UTC, Apaczer commented on assets/translations/Russian
> +No wallpapers available=Изображения для обоев отсутствуют
"Изображения отсутствуют" IMO will be more accurate and won't obscure msgbox space that much on file Browser backdrop

2023-12-24 15:44 UTC, MayanKoyote commented on assets/translations/Russian
> +No wallpapers available=Изображения для обоев отсутствуют
The longer variant was chosen to echo with 'Select an image backdrop=Выбор изображения для задника' и 
'Select an image to use as a wallpaper=Выбор изображения для обоев'.
The longer variant line fits into the length of msgbox, checked (quick replacement on similar situation).
![longversion](https://github.com/MiyooCFW/gmenu2x/assets/43220515/064628c9-3b77-41df-b9b8-7fb63035f87d)
Anyway it's not critical. But if the short variant seems better, then let there be a short variant.

2023-12-24 17:44 UTC, Apaczer commented on assets/translations/Russian
> +No wallpapers available=Изображения для обоев отсутствуют
Then maybe change to "Обои отсутствуют", I want to keep it as close to the original

2024-01-27 21:55 UTC, Apaczer approved these changes

2024-01-30 22:39 UTC, merged